# Generated by Django 4.0.5 on 2023-05-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
